cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'homebrew/dupes'
tap 'homebrew/versions'

brew 'ack'
brew 'coreutils'
brew 'gnu-sed', args: ['--with-default-names']
brew 'gnu-tar', args: ['--with-default-names']
brew 'gnu-which', args: ['--with-default-names']
brew 'grep', args: ['--with-default-names']
brew 'vim',  args: ['--override-system-vi']
brew 'zsh-syntax-highlighting'
brew 'gzip'
brew 'unrar'
brew 'xz'
brew 'screen'
brew 'wget'
brew 'tree'
brew 'openssl'
brew 'readline'
brew 'dos2unix'
brew 'uchardet'
brew 'z'
brew 'zsh'
brew 'bchunk'
brew 'htop'
brew 'nethogs'
brew 'iftop'
brew 'trash'

brew 'git'
brew 'tor'
brew 'zsh-completions'
brew 'go'
brew 'glide'
brew 'jq'
brew 'httpie'
brew 'httping'
brew 'node@4'

cask 'arq'
cask '1password'
cask 'google-chrome'
cask 'transmission'
cask 'vlc'
cask 'sublime'
cask 'sublime-text'
cask 'macdown'
cask 'iterm2'
cask 'sequel-pro'
cask 'messenger'
cask 'postman'
cask 'transmit'
cask 'beardedspice'
cask 'spectacle'
cask 'alfred'
cask 'appcleaner'
cask 'onyx'
cask 'ocenaudio'
cask 'monolingual'
cask 'joinme'
cask 'rcdefaultapp'
cask 'felony'
cask 'docker'
