cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'mas'
brew 'ack'
brew 'coreutils'
brew 'gnu-sed'
brew 'gnu-tar'
brew 'gawk'
brew 'gnu-which'
brew 'grep'
brew 'vim'
brew 'zsh-syntax-highlighting'
brew 'gzip'
brew 'xz'
brew 'screen'
brew 'wget'
brew 'tree'
brew 'openssl'
brew 'readline'
brew 'dos2unix'
brew 'uchardet'
brew 'z'
brew 'zsh', link: true
brew 'bchunk'
brew 'htop'
brew 'nethogs'
brew 'iftop'
brew 'trash'
brew 'p7zip'
brew 'git', link: true
brew 'tor'
brew 'doctl'
brew 'zsh-completions'
brew 'go'
brew 'node', link: true
brew 'jq'
brew 'imagemagick'
brew 'httpie'
brew 'php@8.0', link: true
brew 'composer', args: ['ignore-dependencies']

cask 'arq'
cask '1password'
cask 'finicky'
cask 'google-chrome'
cask 'google-drive'
cask 'transmission'
cask 'vlc'
cask 'sublime-text'
cask 'iterm2'
#cask 'sequel-ace'
cask 'rectangle'
cask 'alfred'
cask 'appcleaner'
cask 'onyx'
#cask 'ocenaudio'
cask 'monolingual'
cask 'swiftdefaultappsprefpane'
cask 'docker'
#cask 'vanilla'
cask 'phpstorm'
cask 'dropbox'
#cask 'balenaetcher'
#cask 'caption'
#cask 'db-browser-for-sqlite'
#cask 'another-redis-desktop-manager'
cask 'imageoptim'
cask 'grammarly'
cask 'kap'
cask 'invisiblix'
#cask 'prefs-editor'
cask 'visual-studio-code'
#cask 'keybase'
cask 'boop'
cask 'insomnia'
cask 'muzzle'
cask 'signal'
cask 'skitch'
cask 'transnomino'
cask 'typora'
cask 'amazon-music'

mas 'Bitwarden', id: 1352778147
mas 'Encrypto', id: 935235287
mas 'Trello', id: 1278508951
mas 'PDFify', id: 1435055351
mas 'Horo', id: 1437226581
mas 'Tailscale', id: 1475387142
