#!/bin/sh

# Computes the growth/decline of two number
# Example:
#   $ incr 40 900 -> 2150.000000%
#   $ incr 50.123 12.987 -> -74.089700%
function incr () {
    n=$(echo "scale=6; 100 * (($2 - $1) / $1)" | bc -l)
    echo "$n%"
}
